### PR TITLE
Feature/setup backend

### PR DESCRIPTION
**Pull request by maismin**
- [x] Connect MongoDB to express app
- [x] Setup eslint configuration
- [x] Setup prettier configuration

### CODE REVIEW

**Comment by vic2019** [comment]
Just two small questions:  Why not put the files under `server/app/` directly under `server/`? Also, what's the benefit of separating `app.js` and `server.js` into two files?

**Comment by maismin** [comment]
> Just two small questions: Why not put the files under `server/app/` directly under `server/`? Also, what's the benefit of separating `app.js` and `server.js` into two files?

I put the files under /server/app because I don't want to pollute the /server directory; if later on during development we decide to add folders named routers that belong to another express app, we will have name conflicts.

The benefit of having a separate app.js and server.js is for testing. I've used jest and supertest for testing API endpoints, and if you combine the app.js and server.js together you'll get a port in use error because each test file calls the combined file, which calls app.listen($port). So I can either:

1. Keep the combined app.js and server.js file. This means that for tests I will need to copy and paste the app.js part into each test file. This violates the DRY principle.
2. Separate the files and import app.js into my tests, which is a better alternative.

**Comment by aeciorc** [comment]
I think this is a solid setup, I will consider moving some of that to our template. Two comments:
* Can you add a .env template file (all keys in the .env, empty values) 
* You need to request reviews instead of assigning us (it's the panel right above)

**Comment by maismin** [comment]
Is there a best practice around env files?

If you checkout a new branch, your untracked env file, and therefore your environment variables, are erased. The env template I pushed to the remote repo only contains keys, so each time you checkout a new branch you need to re-enter the values. Is there an easier solution to this?

Since the keys currently don't contain sensitive info, would it be ok to include the values in the template and do the following instead?
```
cp .env.template .env
```

**Comment by vic2019** [comment]
> Since the keys currently don't contain sensitive info, would it be ok to include the values in the template and do the following instead?
> 
> ```
> cp .env.template .env
> ```
I think it's a good way to go about it. Leave all non-sensitive values in `.env.template` and fill in the rest manually. Thanks!

**Comment by aeciorc** [comment]
> If you checkout a new branch, your untracked env file, and therefore your environment variables, are erased. The env template I pushed to the remote repo only contains keys, so each time you checkout a new branch you need to re-enter the values. Is there an easier solution to this?

This should only happen if you switch from a branch where .env is tracked, into one where it isn't (e.g, switching form the current dev into this branch will cause .env to disappear). However, once your branch is merged into dev and others branch off of it, they can add safely add a .env file again and it won't disappear. That being said, it's fine to have non-sensitive values (like PORT) inside the template.

**Pull request merged**
